import { basecampSeed } from "@basecamp/content";
import {
  applyMigrations,
  createDatabase,
  createPortableExport,
  importPortableExportToPostgres,
  importSeed,
  portableExportTables,
  readPostgresMigrations,
  recordQuickInventoryEntry,
  sqliteMigrationToPostgres,
  upsertEvidenceRecord,
  type PostgresQueryClient,
  type PortableExportArchive
} from "@basecamp/database";
import { describe, expect, it } from "vitest";
import type { QueryResult, QueryResultRow } from "pg";

describe("PostgreSQL production persistence path", () => {
  it("keeps SQLite baseline migrations translatable to PostgreSQL DDL", () => {
    const migrations = readPostgresMigrations();
    const mergedSql = migrations.map((migration) => migration.sql).join("\n");

    expect(migrations.map((migration) => migration.id)).toEqual([
      "0001_basecamp_seed_baseline",
      "0002_household_progress_state",
      "0003_inventory_location_maintenance",
      "0004_offline_sync_commands",
      "0005_drills_skills_evidence",
      "0006_ops_audit",
      "0007_local_auth"
    ]);
    expect(sqliteMigrationToPostgres("server_sequence INTEGER PRIMARY KEY AUTOINCREMENT")).toBe(
      "server_sequence INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    );
    expect(sqliteMigrationToPostgres("applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP")).toBe(
      "applied_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)"
    );
    expect(mergedSql).not.toContain("AUTOINCREMENT");
    expect(mergedSql).not.toContain("sqlite_master");
    expect(mergedSql).not.toContain("PRAGMA");
    expect(mergedSql).toContain("GENERATED BY DEFAULT AS IDENTITY");
  });

  it("imports a SQLite beta portable export through PostgreSQL table and column contracts", async () => {
    const source = createDatabase();

    applyMigrations(source);
    importSeed(source, basecampSeed);
    const entry = recordQuickInventoryEntry(source, {
      itemName: "Postgres bridge water",
      quantity: 2,
      unit: "gallon",
      locationName: "Primary Home Base",
      categoryId: "water",
      type: "water_storage"
    });
    upsertEvidenceRecord(source, {
      kind: "photo",
      title: "Postgres bridge shelf",
      links: [{ entityType: "inventory_event", entityId: entry.event.id }],
      metadata: {
        capturedAt: "2026-08-21T00:00:00.000Z",
        fileName: "postgres-bridge.jpg",
        storageKey: "evidence/postgres-bridge.jpg"
      }
    });

    const archive = createPortableExport(source, {
      appVersion: "0.9.1",
      contentSchemaVersion: basecampSeed.schemaVersion,
      generatedAt: "2026-08-21T00:01:00.000Z"
    });
    const client = new FakePostgresClient(archive);
    const imported = await importPortableExportToPostgres(client, archive, {
      expectedContentSchemaVersion: basecampSeed.schemaVersion,
      importedAt: "2026-08-21T00:02:00.000Z"
    });

    expect(imported.tableCounts.inventory_items).toBe(1);
    expect(imported.tableCounts.evidence_records).toBe(1);
    expect(client.insertedTables).toContain("inventory_items");
    expect(client.insertedTables).toContain("evidence_records");
    expect(client.sqlLog.join("\n")).not.toContain("INSERT OR REPLACE");
    expect(client.sqlLog.join("\n")).not.toContain("?");
    expect(JSON.stringify(archive.evidenceFiles)).not.toContain("/Users/");

    source.close();
  });
});

class FakePostgresClient implements PostgresQueryClient {
  readonly sqlLog: string[] = [];
  readonly insertedTables: string[] = [];
  private readonly tables = new Set<string>(portableExportTables);
  private readonly columns = new Map<string, Set<string>>();

  constructor(archive: PortableExportArchive) {
    for (const table of portableExportTables) {
      const rowColumns = new Set<string>();

      for (const row of archive.tables[table] ?? []) {
        for (const column of Object.keys(row)) {
          rowColumns.add(column);
        }
      }

      this.columns.set(table, rowColumns);
    }
  }

  async query<T extends QueryResultRow = QueryResultRow>(
    text: string,
    values: readonly unknown[] = []
  ): Promise<QueryResult<T>> {
    this.sqlLog.push(text);

    if (text.includes("information_schema.tables")) {
      const table = values[0] as string | undefined;

      if (table === undefined) {
        return this.result(Array.from(this.tables).map((tableName) => ({ table_name: tableName } as T)));
      }

      return this.result(this.tables.has(table) ? [{ table_name: table } as T] : []);
    }

    if (text.includes("information_schema.columns")) {
      const table = values[0] as string;
      const rows = Array.from(this.columns.get(table) ?? []).map((column) => ({ column_name: column } as T));

      return this.result(rows);
    }

    const insertMatch = text.match(/INSERT INTO "([^"]+)"/);

    if (insertMatch?.[1] !== undefined) {
      this.insertedTables.push(insertMatch[1]);
    }

    return this.result([]);
  }

  private result<T extends QueryResultRow>(rows: T[]): QueryResult<T> {
    return {
      command: "",
      rowCount: rows.length,
      oid: 0,
      fields: [],
      rows
    };
  }
}
