import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  createDrillTemplateFromQuest,
  type BasecampSeed
} from "@basecamp/domain";
import {
  assertPortableExportArchiveCompatible,
  portableExportTables,
  type DatabaseRow,
  type PortableExportArchive,
  type PortableImportResult
} from "./operations";
import {
  type MigrationResult,
  type SeedImportResult
} from "./sqlite";
import type { QueryResult, QueryResultRow } from "pg";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const defaultMigrationsDir = path.join(packageRoot, "migrations");

export interface PostgresQueryClient {
  query<T extends QueryResultRow = QueryResultRow>(
    text: string,
    values?: readonly unknown[]
  ): Promise<QueryResult<T>>;
}

export interface PostgresStatus {
  ok: boolean;
  checkedAt: string;
  database: {
    kind: "postgresql";
    migrated: boolean;
    migrationCount: number;
    tableCounts: Record<string, number>;
  };
}

interface SqlMigration {
  id: string;
  sql: string;
}

export function postgresConnectionStringFromEnv(env = process.env): string {
  const value = env.BASECAMP_DATABASE_URL ?? env.DATABASE_URL;

  if (value === undefined || value.trim().length === 0) {
    throw new Error("BASECAMP_DATABASE_URL or DATABASE_URL is required for PostgreSQL operations.");
  }

  return value;
}

export function sqliteMigrationToPostgres(sql: string): string {
  return sql
    .replace(/\bINTEGER PRIMARY KEY AUTOINCREMENT\b/g, "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    .replace(/\bTEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\b/g, "TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)");
}

export function readPostgresMigrations(migrationsDir = defaultMigrationsDir): SqlMigration[] {
  return readdirSync(migrationsDir)
    .filter((file) => file.endsWith(".sql"))
    .sort()
    .map((file) => ({
      id: file.replace(/\.sql$/, ""),
      sql: sqliteMigrationToPostgres(readFileSync(path.join(migrationsDir, file), "utf8"))
    }));
}

export async function applyPostgresMigrations(
  client: PostgresQueryClient,
  migrationsDir = defaultMigrationsDir
): Promise<MigrationResult> {
  await client.query(`
    CREATE TABLE IF NOT EXISTS schema_migrations (
      id TEXT PRIMARY KEY,
      applied_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
    );
  `);

  const applied: string[] = [];
  const skipped: string[] = [];

  for (const migration of readPostgresMigrations(migrationsDir)) {
    const existing = await client.query<{ id: string }>(
      "SELECT id FROM schema_migrations WHERE id = $1",
      [migration.id]
    );

    if (existing.rowCount !== null && existing.rowCount > 0) {
      skipped.push(migration.id);
      continue;
    }

    await client.query("BEGIN");

    try {
      await client.query(migration.sql);
      await client.query("INSERT INTO schema_migrations (id) VALUES ($1)", [migration.id]);
      await client.query("COMMIT");
      applied.push(migration.id);
    } catch (error) {
      await client.query("ROLLBACK");
      throw error;
    }
  }

  return { applied, skipped };
}

export async function importSeedToPostgres(
  client: PostgresQueryClient,
  seed: BasecampSeed
): Promise<SeedImportResult> {
  await client.query("BEGIN");

  try {
    await upsertPostgresRow(client, "seed_imports", {
      schema_version: seed.schemaVersion,
      generated_on: seed.generatedOn
    }, ["schema_version"]);

    for (const category of seed.categories) {
      await upsertPostgresRow(client, "categories", {
        id: category.id,
        name: category.name,
        description: category.description,
        criticality: category.criticality,
        default_pursuit_state: category.defaultPursuitState
      }, ["id"]);
    }

    for (const level of seed.levels) {
      await upsertPostgresRow(client, "capability_levels", {
        id: level.id,
        number: level.number,
        name: level.name,
        duration: level.duration,
        description: level.description
      }, ["id"]);
    }

    for (const quest of seed.quests) {
      await upsertPostgresRow(client, "quest_templates", {
        id: quest.id,
        title: quest.title,
        category_id: quest.categoryId,
        target_level: quest.targetLevel,
        taxonomy_json: JSON.stringify(quest.taxonomy),
        estimated_minutes: quest.estimatedMinutes,
        estimated_cost_usd: quest.estimatedCostUsd,
        xp: quest.xp,
        priority: quest.priority,
        why_it_matters: quest.whyItMatters,
        validation: quest.validation,
        dependencies_json: JSON.stringify(quest.dependencies ?? []),
        accomplishments_json: JSON.stringify(quest.accomplishments ?? []),
        friction_goal_json: quest.frictionGoal === undefined ? null : JSON.stringify(quest.frictionGoal),
        bom_json: quest.bom === undefined ? null : JSON.stringify(quest.bom)
      }, ["id"]);
    }

    for (const quest of seed.quests.filter((candidate) => candidate.taxonomy.includes("drill"))) {
      const template = createDrillTemplateFromQuest(quest);

      await upsertPostgresRow(client, "drill_templates", {
        id: template.id,
        title: template.title,
        category_id: template.categoryId,
        scenario: template.scenario,
        estimated_minutes: template.estimatedMinutes,
        success_criteria_json: JSON.stringify(template.successCriteria),
        evidence_json: JSON.stringify(template.evidence ?? []),
        recommended_quest_ids_json: JSON.stringify(template.recommendedQuestIds ?? []),
        created_at: seed.generatedOn,
        updated_at: seed.generatedOn
      }, ["id"]);
    }

    await client.query("COMMIT");
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  }

  return {
    categories: await countPostgresRows(client, "categories"),
    levels: await countPostgresRows(client, "capability_levels"),
    quests: await countPostgresRows(client, "quest_templates"),
    drillTemplates: await countPostgresRows(client, "drill_templates")
  };
}

export async function importPortableExportToPostgres(
  client: PostgresQueryClient,
  archive: PortableExportArchive,
  options: {
    expectedContentSchemaVersion: string;
    importedAt?: string;
  }
): Promise<PortableImportResult> {
  assertPortableExportArchiveCompatible(archive, {
    expectedContentSchemaVersion: options.expectedContentSchemaVersion
  });

  await client.query("BEGIN");

  try {
    for (const table of [...portableExportTables].reverse()) {
      if (await postgresTableExists(client, table)) {
        await client.query(`DELETE FROM ${quoteIdentifier(table)}`);
      }
    }

    for (const table of portableExportTables) {
      const rows = archive.tables[table] ?? [];

      if (rows.length === 0 || !(await postgresTableExists(client, table))) {
        continue;
      }

      const columns = await postgresTableColumns(client, table);

      for (const row of rows) {
        await insertPostgresRow(client, table, row, columns);
      }
    }

    await resetPostgresIdentity(client, "sync_commands", "server_sequence");
    await client.query("COMMIT");
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  }

  return {
    importedAt: options.importedAt ?? new Date().toISOString(),
    tableCounts: Object.fromEntries(portableExportTables.map((table) => [table, archive.tables[table]?.length ?? 0]))
  };
}

export async function readPostgresStatus(
  client: PostgresQueryClient,
  checkedAt = new Date().toISOString()
): Promise<PostgresStatus> {
  const migrationCount = await countPostgresRows(client, "schema_migrations");
  const tableCounts = await postgresTableCounts(client);

  return {
    ok: migrationCount > 0,
    checkedAt,
    database: {
      kind: "postgresql",
      migrated: migrationCount > 0,
      migrationCount,
      tableCounts
    }
  };
}

export async function countPostgresRows(
  client: PostgresQueryClient,
  table: string
): Promise<number> {
  if (!(await postgresTableExists(client, table))) {
    return 0;
  }

  const result = await client.query<{ count: string }>(
    `SELECT COUNT(*)::text as count FROM ${quoteIdentifier(table)}`
  );

  return Number(result.rows[0]?.count ?? 0);
}

export async function postgresTableCounts(
  client: PostgresQueryClient
): Promise<Record<string, number>> {
  const tables = await client.query<{ table_name: string }>(
    `SELECT table_name
     FROM information_schema.tables
     WHERE table_schema = 'public'
       AND table_type = 'BASE TABLE'
     ORDER BY table_name`
  );
  const counts: Record<string, number> = {};

  for (const row of tables.rows) {
    counts[row.table_name] = await countPostgresRows(client, row.table_name);
  }

  return counts;
}

async function postgresTableExists(client: PostgresQueryClient, table: string): Promise<boolean> {
  const result = await client.query<{ table_name: string }>(
    `SELECT table_name
     FROM information_schema.tables
     WHERE table_schema = 'public'
       AND table_type = 'BASE TABLE'
       AND table_name = $1`,
    [table]
  );

  return result.rowCount !== null && result.rowCount > 0;
}

async function postgresTableColumns(client: PostgresQueryClient, table: string): Promise<Set<string>> {
  const result = await client.query<{ column_name: string }>(
    `SELECT column_name
     FROM information_schema.columns
     WHERE table_schema = 'public'
       AND table_name = $1
     ORDER BY ordinal_position`,
    [table]
  );

  return new Set(result.rows.map((row) => row.column_name));
}

async function upsertPostgresRow(
  client: PostgresQueryClient,
  table: string,
  row: DatabaseRow,
  conflictColumns: string[]
): Promise<void> {
  const columns = Object.keys(row);
  const values = columns.map((column) => row[column] ?? null);
  const placeholders = columns.map((_, index) => `$${index + 1}`).join(", ");
  const updateColumns = columns.filter((column) => !conflictColumns.includes(column));
  const updateClause =
    updateColumns.length === 0
      ? "DO NOTHING"
      : `DO UPDATE SET ${updateColumns
          .map((column) => `${quoteIdentifier(column)} = EXCLUDED.${quoteIdentifier(column)}`)
          .join(", ")}`;

  await client.query(
    `INSERT INTO ${quoteIdentifier(table)} (${columns.map(quoteIdentifier).join(", ")})
     VALUES (${placeholders})
     ON CONFLICT (${conflictColumns.map(quoteIdentifier).join(", ")}) ${updateClause}`,
    values
  );
}

async function insertPostgresRow(
  client: PostgresQueryClient,
  table: string,
  row: DatabaseRow,
  availableColumns: Set<string>
): Promise<void> {
  const columns = Object.keys(row).filter((column) => availableColumns.has(column));

  if (columns.length === 0) {
    return;
  }

  const values = columns.map((column) => row[column] ?? null);
  const placeholders = columns.map((_, index) => `$${index + 1}`).join(", ");

  await client.query(
    `INSERT INTO ${quoteIdentifier(table)} (${columns.map(quoteIdentifier).join(", ")})
     VALUES (${placeholders})`,
    values
  );
}

async function resetPostgresIdentity(
  client: PostgresQueryClient,
  table: string,
  column: string
): Promise<void> {
  if (!(await postgresTableExists(client, table))) {
    return;
  }

  const sequence = await client.query<{ sequence_name: string | null }>(
    "SELECT pg_get_serial_sequence($1, $2) as sequence_name",
    [table, column]
  );
  const sequenceName = sequence.rows[0]?.sequence_name;

  if (sequenceName === undefined || sequenceName === null) {
    return;
  }

  await client.query(
    `SELECT setval(
       $1,
       COALESCE((SELECT MAX(${quoteIdentifier(column)}) FROM ${quoteIdentifier(table)}), 1),
       (SELECT COUNT(*) > 0 FROM ${quoteIdentifier(table)})
     )`,
    [sequenceName]
  );
}

function quoteIdentifier(value: string): string {
  return `"${value.replaceAll('"', '""')}"`;
}
